name: Garbage Pickup data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 15 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v3

      - name: Fetch latest data
        run: |
          ALL_EVENTS=$(curl -s "https://www.berzoras.lt/waste.json" \
            | jq '[.[] | select((.date | strptime("%Y-%m-%d") | mktime) > now)]')

          echo "$ALL_EVENTS" > waste_format.json

          NEXT_DAY_EVENTS=$(echo "$ALL_EVENTS" \
            | jq '[.[] | select((.date | strptime("%Y-%m-%d") | mktime) < (now + 86400))]')

          echo "$NEXT_DAY_EVENTS" | jq -r '.[] | "\(.date) surinkinėjamos \(.name)"' | while read -r REMINDER; do
            curl -d "$REMINDER" ntfy.sh/berzoras_trac_waste
          done

      - name: Commit and push if it changed
        run: |
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
