name: Garbage Pickup data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 15 * * *'
    
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v3
      - name: Fetch latest data
        run: |
          ALL_EVENTS=$(curl -X POST "https://tratc.lt/wp-admin/admin-ajax.php" \
            -H "Accept: */*" \
            -H "Accept-Encoding: gzip, deflate, br" \
            -H "Accept-Language: lt,en-US;q=0.7,en;q=0.3" \
            -H "Connection: keep-alive" \
            -H "Content-Type: application/x-www-form-urlencoded; charset=UTF-8" \
            -H "Cookie: pll_language=lt" \
            -H "DNT: 1" \
            -H "Origin: https://tratc.lt" \
            -H "Referer: https://tratc.lt/plunge/atlieku-surinkimo-grafikai/" \
            -H "Sec-Fetch-Dest: empty" \
            -H "Sec-Fetch-Mode: cors" \
            -H "Sec-Fetch-Site: same-origin" \
            -H "User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/116.0" \
            -H "X-Requested-With: XMLHttpRequest" \
            --data "action=scheduleFilter&filters[municipality]=1&filters[eldership]=6&filters[village]=114&filters[street]=0&filters[house]=0" | jq '[.[] | select(.name? and .date? and .schedule_id? and (.date|type == "string") and ((.date | strptime("%Y-%m-%d") | mktime) > now))]')
          
          echo "$ALL_EVENTS" | jq 'unique_by(.name, .date, .schedule_id)' > waste_format.json

          NEXT_DAY_EVENTS=$(echo "$ALL_EVENTS" | jq '[.[] | select(.name? and .date? and .schedule_id? and (.date|type == "string") and ((.date | strptime("%Y-%m-%d") | mktime) < (now + 86400)))]')

          echo "$NEXT_DAY_EVENTS" | jq -r '.[] | "\(.date) surinkinėjamos \(.name)"' | while read -r REMINDER; do
             curl -d "$REMINDER" ntfy.sh/berzoras_trac_waste
          done
      - name: Commit and push if it changed
        run: |
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
